# Generated by Django 5.1.4 on 2025-03-13 23:12

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('risks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'tb_channel',
            },
        ),
        migrations.CreateModel(
            name='CommunicationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(max_length=50)),
                ('direction', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tb_communication_type',
            },
        ),
        migrations.CreateModel(
            name='Periodicity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'tb_periodicity',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=240, verbose_name='Asunto del Mensaje')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('channels', models.ManyToManyField(related_name='channels', to='communications.channel', verbose_name='Communication Channel')),
                ('communication_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='communication_type', to='communications.communicationtype', verbose_name='Communication Type')),
                ('receivers', models.ManyToManyField(related_name='message_receivers', to='risks.department', verbose_name='Receptor')),
                ('transmitter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transmitter', to='risks.department', verbose_name='Emisor')),
                ('periodicity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='message_periodicity', to='communications.periodicity', verbose_name='Periodicity of Communicaation')),
            ],
            options={
                'db_table': 'tb_message',
            },
        ),
        migrations.CreateModel(
            name='CommunicationTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message='El código debe tener el formato: LLL-LLL-CC', regex='^[A-Za-z]{3}-[A-Za-z]{3}-\\d{2}$')])),
                ('review_number', models.SmallIntegerField()),
                ('review_date', models.DateField()),
                ('approved_by', models.ForeignKey(blank=True, default='Pending Approval', on_delete=django.db.models.deletion.PROTECT, related_name='approved_by', to='risks.department')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_by', to='risks.department')),
                ('reviewed_by', models.ForeignKey(blank=True, default='Pending Review', on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_by', to='risks.department')),
                ('messages', models.ManyToManyField(related_name='messages', to='communications.message')),
            ],
            options={
                'db_table': 'tb_communication_table',
                'ordering': ['id'],
            },
        ),
    ]
