# Generated by Django 5.1.2 on 2025-06-17 17:37

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0003_remove_documentation_document_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'tb_communication_channel',
            },
        ),
        migrations.CreateModel(
            name='CommunicationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(max_length=50)),
                ('direction', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tb_communication_type',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=240, verbose_name='Asunto del Mensaje')),
            ],
            options={
                'db_table': 'tb_communication_message',
            },
        ),
        migrations.CreateModel(
            name='Periodicity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'tb_communication_periodicity',
            },
        ),
        migrations.CreateModel(
            name='CommunicationTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='El código debe tener el formato: LLL-LLL-CC', regex='^[A-Za-z]{3}-[A-Za-z]{3}-\\d{2}$')])),
                ('review_number', models.SmallIntegerField()),
                ('review_date', models.DateField()),
                ('status', models.CharField(choices=[('pending_revision', 'Pendiente de Revisión'), ('pending_approve', 'Pendiente de Aprobación'), ('reviewed', 'Revisada'), ('approved', 'Aprobada'), ('open', 'Abierta (Aceptando Mensajes)')], default='open', max_length=20, null=True)),
                ('summary', models.CharField(blank=True, max_length=400, null=True, verbose_name='Resumen')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_by', to='company.position')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_by', to='company.position')),
                ('emiter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='emiter', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_by', to='company.position')),
            ],
            options={
                'db_table': 'tb_communication_table',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='MessageChanel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='channel', to='communications.channel', verbose_name='Channel')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='message_channels', to='communications.message', verbose_name='Message')),
            ],
            options={
                'db_table': 'tb_communication_channels',
            },
        ),
        migrations.CreateModel(
            name='CommunicationMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='communication_receivers', to=settings.AUTH_USER_MODEL, verbose_name='Receptor')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='message', to='communications.communicationtable', verbose_name='Table')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='communication_type', to='communications.communicationtype', verbose_name='Communication Type')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='communication_message', to='communications.message', verbose_name='Message')),
                ('periodicity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='communication_periodicity', to='communications.periodicity', verbose_name='Periodicity of Communication')),
            ],
            options={
                'db_table': 'tb_communication_messages',
            },
        ),
    ]
