# Generated by Django 5.1.2 on 2025-06-17 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0001_initial'),
        ('company', '0003_remove_documentation_document_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='communicationtable',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='area', to='company.area'),
        ),
    ]
