# Generated by Django 5.1.2 on 2025-03-24 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='update_date',
        ),
    ]
