# Generated by Django 5.1.2 on 2025-06-18 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0002_communicationtable_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communicationtable',
            name='summary',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Resumen'),
        ),
    ]
