# Generated by Django 5.1.2 on 2025-03-24 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0002_remove_message_update_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='update_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
