# Generated by Django 5.1.2 on 2025-03-23 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0002_alter_communicationtable_approved_by_and_more'),
        ('risks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communicationtable',
            name='approved_by',
            field=models.ForeignKey(blank=True, default='Pending Approval', on_delete=django.db.models.deletion.PROTECT, related_name='approved_by', to='risks.department'),
        ),
        migrations.AlterField(
            model_name='communicationtable',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, default='Pending Review', on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_by', to='risks.department'),
        ),
    ]
