# Generated by Django 5.1.2 on 2025-06-19 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0003_alter_communicationtable_summary'),
        ('company', '0005_alter_userposition_position_alter_userposition_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communicationmessage',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='communication_receivers', to='company.position', verbose_name='Receptor'),
        ),
        migrations.AlterField(
            model_name='communicationtable',
            name='emiter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='emiter', to='company.position'),
        ),
    ]
