# Generated by Django 5.1.2 on 2025-03-24 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0003_alter_communicationtable_approved_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='update_date',
        ),
    ]
