# Generated by Django 5.1.2 on 2025-03-26 21:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0002_alter_audited_audited_person_alter_auditteam_person_and_more'),
        ('communications', '0003_message_update_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='communicationtable',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='area', to='audits.area'),
        ),
        migrations.AddField(
            model_name='communicationtable',
            name='status',
            field=models.CharField(choices=[('pending_revision', 'Pendiente de Revisión'), ('pending_approve', 'Pendiente de Aprobación'), ('reviewed', 'Revisada'), ('approved', 'Aprobada'), ('open', 'Abierta (Aceptando Mensajes)')], default='abierta', max_length=20),
        ),
        migrations.AlterField(
            model_name='communicationtable',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='communicationtable',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='communicationtable',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='message',
            name='receivers',
            field=models.ManyToManyField(related_name='message_receivers', to=settings.AUTH_USER_MODEL, verbose_name='Receptor'),
        ),
        migrations.AlterField(
            model_name='message',
            name='transmitter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transmitter', to=settings.AUTH_USER_MODEL, verbose_name='Emisor'),
        ),
    ]
