# Generated by Django 5.1.4 on 2025-04-07 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0004_communicationtable_area_communicationtable_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communicationtable',
            name='status',
            field=models.CharField(choices=[('pending_revision', 'Pendiente de Revisión'), ('pending_approve', 'Pendiente de Aprobación'), ('reviewed', 'Revisada'), ('approved', 'Aprobada'), ('open', 'Abierta (Aceptando Mensajes)')], default='open', max_length=20),
        ),
    ]
