# Generated by Django 5.1.2 on 2025-06-20 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0005_alter_messagechanel_channel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communicationtable',
            name='area',
        ),
    ]
