# Generated by Django 5.1.4 on 2025-04-22 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0005_alter_communicationtable_status'),
        ('company', '0002_area_parent_alter_area_name_alter_area_users_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communicationtable',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='area', to='company.area'),
        ),
    ]
