# Generated by Django 5.1.2 on 2025-05-12 13:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0006_alter_communicationtable_area'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='subject',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='communicationtable',
            name='messages',
        ),
        migrations.RemoveField(
            model_name='message',
            name='channels',
        ),
        migrations.RemoveField(
            model_name='message',
            name='communication_type',
        ),
        migrations.RemoveField(
            model_name='message',
            name='creation_date',
        ),
        migrations.RemoveField(
            model_name='message',
            name='periodicity',
        ),
        migrations.RemoveField(
            model_name='message',
            name='receivers',
        ),
        migrations.RemoveField(
            model_name='message',
            name='transmitter',
        ),
        migrations.RemoveField(
            model_name='message',
            name='update_date',
        ),
        migrations.AddField(
            model_name='communicationtable',
            name='emiter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='emiter', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='communicationtable',
            name='status',
            field=models.CharField(choices=[('pending_revision', 'Pendiente de Revisión'), ('pending_approve', 'Pendiente de Aprobación'), ('reviewed', 'Revisada'), ('approved', 'Aprobada'), ('open', 'Abierta (Aceptando Mensajes)')], default='open', max_length=20, null=True),
        ),
        migrations.AlterModelTable(
            name='channel',
            table='tb_communication_channel',
        ),
        migrations.AlterModelTable(
            name='message',
            table='tb_communication_message',
        ),
        migrations.AlterModelTable(
            name='periodicity',
            table='tb_communication_periodicity',
        ),
        migrations.CreateModel(
            name='CommunicationMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='communication_message', to='communications.communicationtype', verbose_name='Communication Type')),
                ('periodicity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='communication_periodicity', to='communications.periodicity', verbose_name='Periodicity of Communication')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='communication_receivers', to=settings.AUTH_USER_MODEL, verbose_name='Receptor')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Table', to='communications.communicationtype', verbose_name='Table')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='communication_type', to='communications.communicationtype', verbose_name='Communication Type')),
            ],
            options={
                'db_table': 'tb_communication_messages',
            },
        ),
        migrations.CreateModel(
            name='MessageChanel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='channel', to='communications.channel', verbose_name='Channel')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='message', to='communications.message', verbose_name='Message')),
            ],
            options={
                'db_table': 'tb_communication_channels',
            },
        ),
    ]
