# Generated by Django 5.1.2 on 2025-06-23 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0006_remove_communicationtable_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagechanel',
            name='table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='message_channels', to='communications.communicationtable', verbose_name='Channel'),
        ),
    ]
