# Generated by Django 5.1.2 on 2025-05-12 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0007_rename_subject_message_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communicationmessage',
            name='creation_date',
        ),
        migrations.RemoveField(
            model_name='communicationmessage',
            name='update_date',
        ),
    ]
