# Generated by Django 5.1.2 on 2025-05-20 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0008_remove_communicationmessage_creation_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communicationmessage',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='communication_message', to='communications.message', verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='communicationmessage',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='communication_table', to='communications.communicationtable', verbose_name='Table'),
        ),
    ]
