# Generated by Django 5.1.2 on 2025-05-20 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0009_alter_communicationmessage_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communicationmessage',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='message', to='communications.communicationtable', verbose_name='Table'),
        ),
    ]
