# Generated by Django 5.1.2 on 2025-06-01 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0010_alter_communicationmessage_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagechanel',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='message_channels', to='communications.channel', verbose_name='Channel'),
        ),
    ]
