# Generated by Django 5.1.2 on 2025-06-01 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0011_alter_messagechanel_channel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagechanel',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='channel', to='communications.channel', verbose_name='Channel'),
        ),
        migrations.AlterField(
            model_name='messagechanel',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='message_channels', to='communications.message', verbose_name='Message'),
        ),
    ]
