# Generated by Django 5.1.2 on 2025-04-16 10:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('audits', '0003_alter_findings_classification_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('order', models.IntegerField()),
            ],
            options={
                'db_table': 'tb_activity',
            },
        ),
        migrations.CreateModel(
            name='Documentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField(choices=[('procedure', 'Procedure'), ('instructions', 'Instructions'), ('method', 'Method')])),
                ('description', models.TextField()),
                ('documentation_code', models.TextField()),
            ],
            options={
                'db_table': 'tb_documentation',
            },
        ),
        migrations.CreateModel(
            name='ExternalClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
            options={
                'db_table': 'tb_external_client',
            },
        ),
        migrations.CreateModel(
            name='ExternalSupplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
            options={
                'db_table': 'tb_external_supplier',
            },
        ),
        migrations.CreateModel(
            name='PerformanceIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('effective', models.BooleanField(default=False)),
                ('efficient', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'tb_performance_indicator',
            },
        ),
        migrations.CreateModel(
            name='ProcessInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'tb_process_input',
            },
        ),
        migrations.CreateModel(
            name='ProcessMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measurement_type', models.TextField()),
                ('description', models.TextField()),
                ('range', models.TextField(blank=True, null=True)),
                ('equipment', models.TextField()),
            ],
            options={
                'db_table': 'tb_measurement',
            },
        ),
        migrations.CreateModel(
            name='ProcessOutput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'tb_process_output',
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField()),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'tb_resource',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('type', models.TextField(choices=[('internal', 'Internal'), ('external', 'External')])),
                ('internal_client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clients', to='audits.area')),
                ('external_client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clients', to='processes.externalclient')),
            ],
            options={
                'db_table': 'tb_client',
            },
        ),
        migrations.CreateModel(
            name='JobPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('position_code', models.TextField()),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='job_positions', to='audits.area')),
            ],
            options={
                'db_table': 'tb_job_position',
            },
        ),
        migrations.CreateModel(
            name='PositionRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.TextField()),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='processes.jobposition')),
            ],
            options={
                'db_table': 'tb_position_role',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('type', models.TextField(choices=[('internal', 'Internal'), ('external', 'External')])),
                ('external_supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='suppliers', to='processes.externalsupplier')),
                ('internal_supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='suppliers', to='audits.area')),
            ],
            options={
                'db_table': 'tb_supplier',
            },
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('objective', models.TextField()),
                ('creation_date', models.DateField()),
                ('process_code', models.TextField()),
                ('review', models.TextField(blank=True, null=True)),
                ('review_date', models.DateField(blank=True, null=True)),
                ('sheet', models.TextField()),
                ('activities', models.ManyToManyField(related_name='processes', to='processes.activity')),
                ('clients', models.ManyToManyField(related_name='processes', to='processes.client')),
                ('documents', models.ManyToManyField(related_name='processes', to='processes.documentation')),
                ('indicators', models.ManyToManyField(related_name='processes', to='processes.performanceindicator')),
                ('positions', models.ManyToManyField(related_name='processes', to='processes.positionrole')),
                ('responsible', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='processes', to=settings.AUTH_USER_MODEL)),
                ('inputs', models.ManyToManyField(related_name='processes', to='processes.processinput')),
                ('measurements', models.ManyToManyField(related_name='processes', to='processes.processmeasurement')),
                ('outputs', models.ManyToManyField(related_name='processes', to='processes.processoutput')),
                ('resources', models.ManyToManyField(related_name='processes', to='processes.resource')),
                ('suppliers', models.ManyToManyField(related_name='processes', to='processes.supplier')),
            ],
            options={
                'db_table': 'tb_process',
            },
        ),
    ]
