# Generated by Django 5.1.2 on 2025-04-22 15:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('effective', models.BooleanField(default=False)),
                ('efficient', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'tb_performance_indicator',
            },
        ),
        migrations.CreateModel(
            name='ProcessInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
            options={
                'db_table': 'tb_process_input_aux',
            },
        ),
        migrations.CreateModel(
            name='ProcessOutput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
            options={
                'db_table': 'tb_process_output_aux',
            },
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('objective', models.TextField()),
                ('creation_date', models.DateField()),
                ('process_code', models.TextField()),
                ('review', models.TextField(blank=True, null=True)),
                ('review_date', models.DateField(blank=True, null=True)),
                ('staff_roles', models.TextField(blank=True, null=True)),
                ('workspaces', models.TextField(blank=True, null=True)),
                ('facilities', models.TextField(blank=True, null=True)),
                ('equipment', models.TextField(blank=True, null=True)),
                ('materials', models.TextField(blank=True, null=True)),
                ('transport_resources', models.TextField(blank=True, null=True)),
                ('communication_technologies', models.TextField(blank=True, null=True)),
                ('operational_environment', models.TextField(blank=True, null=True)),
                ('documents', models.ManyToManyField(related_name='process', to='company.documentation')),
                ('external_clients', models.ManyToManyField(blank=True, related_name='process_external_client', to='company.externalclient')),
                ('external_suppliers', models.ManyToManyField(blank=True, related_name='process_external_supplier', to='company.externalsupplier')),
                ('internal_clients', models.ManyToManyField(blank=True, related_name='process_internal_client', to='company.area')),
                ('internal_suppliers', models.ManyToManyField(blank=True, related_name='process_internal_supplier', to='company.area')),
                ('performance_indicators', models.ManyToManyField(related_name='processes', to='processes.performanceindicator')),
                ('responsible', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='process', to=settings.AUTH_USER_MODEL)),
                ('inputs', models.ManyToManyField(related_name='process', to='processes.processinput')),
                ('outputs', models.ManyToManyField(related_name='process', to='processes.processoutput')),
            ],
            options={
                'db_table': 'tb_process',
            },
        ),
        migrations.CreateModel(
            name='ProcessActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.TextField()),
                ('order', models.PositiveIntegerField()),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='processes.process')),
            ],
            options={
                'db_table': 'tb_process_activities',
            },
        ),
        migrations.CreateModel(
            name='ProcessMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measurement_process_parameter', models.TextField()),
                ('measurement_process_range', models.TextField(blank=True, null=True)),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='processes.process')),
            ],
            options={
                'db_table': 'tb_process_measurement_process',
            },
        ),
        migrations.CreateModel(
            name='ProcessPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.position')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='processes.process')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.rol')),
            ],
            options={
                'db_table': 'tb_process_positions',
            },
        ),
        migrations.CreateModel(
            name='ProductMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measurement_product_parameter', models.TextField()),
                ('measurement_product_range', models.TextField(blank=True, null=True)),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='processes.process')),
            ],
            options={
                'db_table': 'tb_process_measurement_product',
            },
        ),
    ]
