# Generated by Django 5.1.2 on 2025-04-29 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='processmeasurement',
            name='measurement_process_equipment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productmeasurement',
            name='measurement_product_equipment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
