# Generated by Django 5.1.2 on 2025-06-20 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0002_processmeasurement_measurement_process_equipment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='summary',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Resumen'),
        ),
    ]
