# Generated by Django 5.1.2 on 2025-06-20 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_alter_userposition_position_alter_userposition_user'),
        ('processes', '0003_process_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='responsible',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='process', to='company.position'),
        ),
    ]
