# Generated by Django 5.2.3 on 2025-06-29 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0004_alter_process_responsible'),
    ]

    operations = [
        migrations.AddField(
            model_name='processmeasurement',
            name='equipment',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='productmeasurement',
            name='equipment',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
