# Generated by Django 5.2.3 on 2025-06-29 22:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0005_processmeasurement_equipment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessMeasurementRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measurement_name', models.TextField(verbose_name='Measurement Name')),
                ('date', models.DateField(verbose_name='Date')),
                ('measured_value', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Measured Value')),
                ('target_value', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Target Value')),
                ('unit', models.TextField(blank=True, null=True, verbose_name='Unit')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Comment')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='processes.process', verbose_name='Process')),
            ],
            options={
                'db_table': 'tb_process_measurement_records',
            },
        ),
        migrations.CreateModel(
            name='ProcessPerformanceMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('measured_value', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Measured Value')),
                ('target_value', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Target Value')),
                ('unit', models.TextField(blank=True, null=True, verbose_name='Unit')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Comment')),
                ('performance_indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='processes.performanceindicator', verbose_name='Performance Indicator')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='processes.process', verbose_name='Process')),
            ],
            options={
                'db_table': 'tb_process_performance_measurements',
            },
        ),
        migrations.CreateModel(
            name='ProductMeasurementRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measurement_name', models.TextField(verbose_name='Measurement Name')),
                ('product_reference', models.TextField(verbose_name='Product Reference')),
                ('date', models.DateField(verbose_name='Date')),
                ('measured_value', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Measured Value')),
                ('tolerance_min', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Tolerance Min')),
                ('tolerance_max', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Tolerance Max')),
                ('unit', models.TextField(verbose_name='Unit')),
                ('result_ok', models.BooleanField(verbose_name='Result OK')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Comment')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='processes.process', verbose_name='Process')),
            ],
            options={
                'db_table': 'tb_product_measurement_records',
            },
        ),
    ]
