# Generated by Django 5.2.3 on 2025-06-30 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0006_processmeasurementrecord_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessPerformanceIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_acceptable_value', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('max_acceptable_value', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('min_max', models.CharField(blank=True, choices=[('min', 'Min'), ('max', 'Max'), ('range', 'Range')], max_length=10, null=True)),
            ],
            options={
                'db_table': 'tb_process_performance_indicators',
                'managed': False,
            },
        ),
    ]
