# Generated by Django 5.2.3 on 2025-06-30 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0007_processperformanceindicator'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProcessPerformanceIndicator',
        ),
        migrations.RemoveField(
            model_name='processmeasurementrecord',
            name='process',
        ),
        migrations.RemoveField(
            model_name='productmeasurementrecord',
            name='process',
        ),
        migrations.AddField(
            model_name='processmeasurementrecord',
            name='process_measurement',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='processes.processmeasurement', verbose_name='Process Measurement'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productmeasurementrecord',
            name='product_measurement',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='processes.productmeasurement', verbose_name='Product Measurement'),
            preserve_default=False,
        ),
    ]
