# Generated by Django 5.2.3 on 2025-06-30 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0008_delete_processperformanceindicator_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processmeasurement',
            name='equipment',
        ),
        migrations.DeleteModel(
            name='ProcessPerformanceMeasurement',
        ),
    ]
