# Generated by Django 5.2.3 on 2025-07-01 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0009_remove_processmeasurement_equipment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessPerformanceIndicators',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('min_acceptable_value', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('max_acceptable_value', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('min_max', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tb_process_performance_indicators',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProcessPerformanceMeasurements',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('measured_value', models.DecimalField(decimal_places=3, max_digits=10)),
                ('target_value', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('unit', models.TextField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tb_process_performance_measurements',
                'managed': False,
            },
        ),
    ]
