# Generated by Django 5.2.3 on 2025-06-16 15:51

import django.db.models.deletion
import multiselectfield.db.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0003_remove_documentation_document_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskIdentification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_name', models.CharField(max_length=255)),
                ('identified_risk', models.CharField(max_length=255, unique=True)),
                ('consequences', models.TextField()),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risks', to='company.area')),
            ],
            options={
                'db_table': 'tb_risks_identification',
            },
        ),
        migrations.CreateModel(
            name='RiskEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')])),
                ('current_preventive_controls', models.TextField(blank=True, null=True)),
                ('occurrence', models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')])),
                ('current_detection_controls', models.TextField(blank=True, null=True)),
                ('detection', models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')])),
                ('risk_level', models.CharField(choices=[('High', 'High'), ('Moderate', 'Moderate'), ('Low', 'Low')], max_length=10)),
                ('risk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='risks.riskidentification')),
            ],
            options={
                'db_table': 'tb_risks_evaluation',
            },
        ),
        migrations.CreateModel(
            name='Reevaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.PositiveIntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=0)),
                ('occurrence', models.PositiveIntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=0)),
                ('detection', models.PositiveIntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=0)),
                ('risk_level', models.CharField(choices=[('High', 'High'), ('Moderate', 'Moderate'), ('Low', 'Low')], max_length=10)),
                ('risk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reevaluations', to='risks.riskidentification')),
            ],
            options={
                'db_table': 'tb_risks_reevaluation',
            },
        ),
        migrations.CreateModel(
            name='ContingencyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contingency_actions', multiselectfield.db.fields.MultiSelectField(choices=[('N/A', 'N/A'), ('ALT_PROCEDURES', 'Establecer procedimientos alternativos'), ('ALT_SUPPLIERS', 'Identificar proveedores sustitutos'), ('BACKUP_STAFF', 'Asignar personal de respaldo'), ('EMERGENCY_STOCK', 'Mantener inventarios de emergencia'), ('TECH_REDUNDANCY', 'Implementar redundancias tecnológicas'), ('CRISIS_COMM', 'Establecer protocolos de comunicación de crisis'), ('DRILLS', 'Realizar simulacros y pruebas periódicas'), ('INSURANCE', 'Contratar seguros o coberturas específicas'), ('OUTSOURCE', 'Externalizar temporalmente operaciones críticas'), ('MANUALS', 'Crear manuales de operación ante fallos')], max_length=124)),
                ('communicate_to', models.ManyToManyField(related_name='communicate_to_contingency', to=settings.AUTH_USER_MODEL)),
                ('responsible', models.ManyToManyField(related_name='responsible_for_contingency', to=settings.AUTH_USER_MODEL)),
                ('risk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='risks.riskidentification')),
            ],
            options={
                'db_table': 'tb_risks_contingency_plan',
            },
        ),
        migrations.CreateModel(
            name='RiskTreatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treatment_action', models.TextField()),
                ('target_date', models.DateField()),
                ('actual_date', models.DateField()),
                ('responsible', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('risk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatments', to='risks.riskidentification')),
            ],
            options={
                'db_table': 'tb_risks_treatment',
            },
        ),
    ]
