# Generated by Django 5.1.4 on 2025-03-13 23:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContingencyAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'tb_contingency_action',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'tb_department',
            },
        ),
        migrations.CreateModel(
            name='RiskLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=50, unique=True)),
                ('color', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tb_risk_level',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'tb_role',
            },
        ),
        migrations.CreateModel(
            name='RiskIdentification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_name', models.CharField(max_length=255)),
                ('identified_risk', models.CharField(max_length=255, unique=True)),
                ('consequences', models.TextField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risks', to='risks.department')),
            ],
            options={
                'db_table': 'tb_risk_identification',
            },
        ),
        migrations.CreateModel(
            name='RiskEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], verbose_name='Severity')),
                ('current_preventive_controls', models.TextField(blank=True, null=True, verbose_name='Current Preventive Controls')),
                ('occurrence', models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], verbose_name='Occurrence')),
                ('current_detection_controls', models.TextField(blank=True, null=True, verbose_name='Current Detection Controls')),
                ('detection', models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], verbose_name='Detection')),
                ('risk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='risks.riskidentification')),
                ('risk_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='risks.risklevel', verbose_name='Risk Level')),
            ],
            options={
                'db_table': 'tb_risk_evaluation',
            },
        ),
        migrations.CreateModel(
            name='Reevaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.PositiveIntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=0)),
                ('occurrence', models.PositiveIntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=0)),
                ('detection', models.PositiveIntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=0)),
                ('risk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reevaluations', to='risks.riskidentification')),
                ('risk_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reevaluations', to='risks.risklevel')),
            ],
            options={
                'db_table': 'tb_reevaluation',
            },
        ),
        migrations.CreateModel(
            name='RiskTreatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treatment_action', models.TextField(verbose_name='Treatment Action')),
                ('target_date', models.DateField(verbose_name='Target Date')),
                ('actual_date', models.DateField(verbose_name='Actual Date')),
                ('risk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatments', to='risks.riskidentification')),
                ('responsible', models.ManyToManyField(to='risks.role', verbose_name='Responsible')),
            ],
            options={
                'db_table': 'tb_risk_treatment',
            },
        ),
        migrations.CreateModel(
            name='ContingencyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contingency_actions', models.ManyToManyField(to='risks.contingencyaction', verbose_name='Contingency Actions')),
                ('risk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='risks.riskidentification')),
                ('communicate_to', models.ManyToManyField(related_name='communicate_to_contingency', to='risks.role', verbose_name='Communicate To')),
                ('responsible', models.ManyToManyField(related_name='responsible_for_contingency', to='risks.role', verbose_name='Responsible')),
            ],
            options={
                'db_table': 'tb_contingency_plan',
            },
        ),
    ]
