# Generated by Django 5.2.3 on 2025-06-26 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0004_alter_process_responsible'),
        ('risks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='riskidentification',
            name='activity_name',
        ),
        migrations.AddField(
            model_name='riskidentification',
            name='process',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='risks', to='processes.process'),
            preserve_default=False,
        ),
    ]
