# Generated by Django 5.1.4 on 2025-04-24 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_area_parent_alter_area_name_alter_area_users_and_more'),
        ('risks', '0002_alter_riskevaluation_risk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='riskidentification',
            name='department',
        ),
        migrations.AddField(
            model_name='riskidentification',
            name='area',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='risks', to='company.area'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contingencyplan',
            name='communicate_to',
            field=models.ManyToManyField(related_name='communicate_to_contingency', to='risks.role'),
        ),
        migrations.AlterField(
            model_name='contingencyplan',
            name='contingency_actions',
            field=models.ManyToManyField(to='risks.contingencyaction'),
        ),
        migrations.AlterField(
            model_name='contingencyplan',
            name='responsible',
            field=models.ManyToManyField(related_name='responsible_for_contingency', to='risks.role'),
        ),
        migrations.AlterField(
            model_name='riskevaluation',
            name='current_detection_controls',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='riskevaluation',
            name='current_preventive_controls',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='riskevaluation',
            name='detection',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')]),
        ),
        migrations.AlterField(
            model_name='riskevaluation',
            name='occurrence',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')]),
        ),
        migrations.AlterField(
            model_name='riskevaluation',
            name='risk_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='risks.risklevel'),
        ),
        migrations.AlterField(
            model_name='riskevaluation',
            name='severity',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')]),
        ),
        migrations.AlterField(
            model_name='risktreatment',
            name='actual_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='risktreatment',
            name='responsible',
            field=models.ManyToManyField(to='risks.role'),
        ),
        migrations.AlterField(
            model_name='risktreatment',
            name='target_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='risktreatment',
            name='treatment_action',
            field=models.TextField(),
        ),
        migrations.AlterModelTable(
            name='contingencyaction',
            table='tb_risks_contingency_action',
        ),
        migrations.AlterModelTable(
            name='contingencyplan',
            table='tb_risks_contingency_plan',
        ),
        migrations.AlterModelTable(
            name='reevaluation',
            table='tb_risks_reevaluation',
        ),
        migrations.AlterModelTable(
            name='riskevaluation',
            table='tb_risks_evaluation',
        ),
        migrations.AlterModelTable(
            name='riskidentification',
            table='tb_risks_identification',
        ),
        migrations.AlterModelTable(
            name='risklevel',
            table='tb_risks_level',
        ),
        migrations.AlterModelTable(
            name='risktreatment',
            table='tb_risks_treatment',
        ),
        migrations.AlterModelTable(
            name='role',
            table='tb_risks_role',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
    ]
