# Generated by Django 5.2.3 on 2025-06-27 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_alter_userposition_position_alter_userposition_user'),
        ('risks', '0002_remove_riskidentification_activity_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contingencyplan',
            name='communicate_to',
            field=models.ManyToManyField(related_name='communicate_to_contingency', to='company.position'),
        ),
        migrations.AlterField(
            model_name='contingencyplan',
            name='responsible',
            field=models.ManyToManyField(related_name='responsible_for_contingency', to='company.position'),
        ),
        migrations.AlterField(
            model_name='risktreatment',
            name='responsible',
            field=models.ManyToManyField(to='company.position'),
        ),
    ]
