# Generated by Django 5.2.3 on 2025-06-29 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risks', '0003_alter_contingencyplan_communicate_to_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskidentification',
            name='source',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
