# Generated by Django 5.2.3 on 2025-06-29 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_externalsupplier_country_and_more'),
        ('risks', '0004_riskidentification_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContingencyPlanCommunicateTo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'tb_risks_contingency_plan_communicate_to',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ContingencyPlanResponsible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'tb_risks_contingency_plan_responsible',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='contingencyplan',
            name='communicate_to',
            field=models.ManyToManyField(related_name='communicate_to_contingency', through='risks.ContingencyPlanCommunicateTo', to='company.position'),
        ),
        migrations.AlterField(
            model_name='contingencyplan',
            name='responsible',
            field=models.ManyToManyField(related_name='responsible_for_contingency', through='risks.ContingencyPlanResponsible', to='company.position'),
        ),
    ]
