# Generated by Django 5.2.3 on 2025-06-16 15:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0003_remove_documentation_document_type_and_more'),
        ('processes', '0002_processmeasurement_measurement_process_equipment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditProgramHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Year')),
                ('objective', models.TextField(verbose_name='Objective')),
                ('scope', models.TextField(verbose_name='Scope')),
                ('audit_criteria', models.TextField(verbose_name='Audit Criteria')),
                ('security_standards', models.TextField(verbose_name='Security Standards')),
            ],
            options={
                'db_table': 'tb_audit_annual_program_headers',
            },
        ),
        migrations.CreateModel(
            name='LeadAuditorEvaluationQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(verbose_name='Question Text')),
                ('type', models.TextField(choices=[('AUDITADO', 'AUDITADO'), ('AUDITOR_LIDER', 'AUDITOR_LIDER')], verbose_name='Type')),
            ],
            options={
                'db_table': 'tb_audit_auditor_questions',
            },
        ),
        migrations.CreateModel(
            name='AnnualProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveSmallIntegerField(verbose_name='Month')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_annual_programs', to='processes.process', verbose_name='Process')),
                ('program_header', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='annual_programs', to='audits.auditprogramheader', verbose_name='Program Header')),
            ],
            options={
                'db_table': 'tb_audit_annual_program',
            },
        ),
        migrations.CreateModel(
            name='AnnualPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audit_opening_date', models.DateField(verbose_name='Audit Opening Date')),
                ('audit_opening_time', models.TimeField(verbose_name='Audit Opening Time')),
                ('audit_opening_location', models.TextField(verbose_name='Audit Opening Location')),
                ('audit_closing_date', models.DateField(verbose_name='Audit Closing Date')),
                ('audit_closing_time', models.TimeField(verbose_name='Audit Closing Time')),
                ('audit_closing_location', models.TextField(verbose_name='Audit Closing Location')),
                ('lider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='annual_plans', to=settings.AUTH_USER_MODEL, verbose_name='Audit Leader')),
                ('annual_program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='annual_plans', to='audits.annualprogram', verbose_name='Annual Program')),
            ],
            options={
                'db_table': 'tb_audit_annual_plan',
            },
        ),
        migrations.CreateModel(
            name='AuditedEvaluationQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(verbose_name='Question Text')),
                ('requirement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='company.requirement', verbose_name='Requirement')),
            ],
            options={
                'db_table': 'tb_audit_checklist_questions',
            },
        ),
        migrations.CreateModel(
            name='AuditorEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.SmallIntegerField(verbose_name='Order in Checklist')),
                ('rate', models.IntegerField(verbose_name='Assigned Rating')),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='auditor_evaluations', to='audits.annualplan', verbose_name='Audit')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='auditor_evaluations', to='audits.auditedevaluationquestion', verbose_name='Question')),
            ],
            options={
                'db_table': 'tb_audit_auditor_evaluation',
            },
        ),
        migrations.CreateModel(
            name='AuditReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField(verbose_name='Summary of Audit Development')),
                ('strengths', models.TextField(verbose_name='Strengths')),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='audits.annualprogram', verbose_name='Audit Plan')),
            ],
            options={
                'db_table': 'tb_audit_report',
            },
        ),
        migrations.CreateModel(
            name='Checklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveSmallIntegerField(verbose_name='Order')),
                ('compliance', models.BooleanField(verbose_name='Compliance')),
                ('evidence', models.TextField(blank=True, null=True, verbose_name='Objective Evidence')),
                ('audit_plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checklists', to='audits.annualplan', verbose_name='Audit Plan')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checklists', to='audits.auditedevaluationquestion', verbose_name='Question')),
            ],
            options={
                'db_table': 'tb_audit_checklist',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Findings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finding_text', models.TextField(verbose_name='Finding')),
                ('classification', models.CharField(choices=[('NC_MAYOR', 'NC_MAYOR'), ('NC_MENOR', 'NC_MENOR'), ('OPORTUNIDAD_MEJORA', 'OPORTUNIDAD_MEJORA')], max_length=20, verbose_name='Finding Classification')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='audits.auditreport', verbose_name='Audit Report')),
                ('requirement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='company.requirement', verbose_name='Requirement')),
            ],
            options={
                'db_table': 'tb_audit_findings',
            },
        ),
        migrations.CreateModel(
            name='AnnualPlanAudited',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annual_plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audited_users', to='audits.annualplan', verbose_name='Audit Plan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audited_users', to=settings.AUTH_USER_MODEL, verbose_name='Audited User')),
            ],
            options={
                'db_table': 'tb_audit_annual_plan_audited',
                'unique_together': {('annual_plan', 'user')},
            },
        ),
        migrations.CreateModel(
            name='AnnualPlanAuditor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annual_plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='auditors', to='audits.annualplan', verbose_name='Audit Plan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='auditors', to=settings.AUTH_USER_MODEL, verbose_name='Auditor')),
            ],
            options={
                'db_table': 'tb_audit_annual_plan_auditors',
                'unique_together': {('annual_plan', 'user')},
            },
        ),
        migrations.CreateModel(
            name='AnnualProgramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annual_program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='users', to='audits.annualprogram', verbose_name='Annual Program')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='annual_programs', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'db_table': 'tb_audit_annual_program_users',
                'unique_together': {('annual_program', 'user')},
            },
        ),
        migrations.CreateModel(
            name='ProcessRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='processes.process')),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.requirement')),
            ],
            options={
                'db_table': 'tb_audit_process_requirements',
                'unique_together': {('process', 'requirement')},
            },
        ),
    ]
