# Generated by Django 5.1.2 on 2025-03-22 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audited',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'tb_audited',
            },
        ),
        migrations.CreateModel(
            name='AuditPlanHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening_meeting_location', models.CharField(max_length=200, verbose_name='Opening Meeting Location')),
                ('opening_meeting_date_time', models.DateTimeField(verbose_name='Opening Meeting Date and Time')),
                ('closing_meeting_location', models.CharField(max_length=200, verbose_name='Closing Meeting Location')),
                ('closing_meeting_date_time', models.DateTimeField(verbose_name='Closing Meeting Date and Time')),
            ],
            options={
                'db_table': 'tb_audit_plan_header',
            },
        ),
        migrations.CreateModel(
            name='AuditProgramHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objective', models.TextField(verbose_name='Objective')),
                ('scope', models.TextField(verbose_name='Scope')),
                ('audit_criteria', models.TextField(verbose_name='Audit Criteria')),
                ('security_standards', models.TextField(verbose_name='Security Standards')),
            ],
            options={
                'db_table': 'tb_audit_program_header',
            },
        ),
        migrations.CreateModel(
            name='AuditReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField(verbose_name='Summary of Audit Development')),
                ('strengths', models.TextField(verbose_name='Strengths')),
            ],
            options={
                'db_table': 'tb_audit_report',
            },
        ),
        migrations.CreateModel(
            name='AuditRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Audit Team Role')),
            ],
            options={
                'db_table': 'tb_audit_role',
            },
        ),
        migrations.CreateModel(
            name='FindingClassification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classification', models.CharField(choices=[('minor_non_conformity', 'Minor Non-Conformity'), ('major_non_conformity', 'Major Non-Conformity'), ('improvement_opportunity', 'Improvement Opportunity')], max_length=50, verbose_name='Classification')),
            ],
            options={
                'db_table': 'tb_finding_classification',
            },
        ),
        migrations.CreateModel(
            name='ParentArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Parent Area Name')),
            ],
            options={
                'db_table': 'tb_parent_area',
            },
        ),
        migrations.CreateModel(
            name='RequirementLevel1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Requirement Level 1')),
            ],
            options={
                'db_table': 'tb_requirement_level1',
            },
        ),
        migrations.CreateModel(
            name='AuditedEvaluationQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=500, verbose_name='Question Text')),
                ('order', models.IntegerField(verbose_name='Order')),
                ('audited', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audited_questions', to='audits.audited', verbose_name='Audited')),
            ],
            options={
                'db_table': 'tb_audited_evaluation_question',
            },
        ),
        migrations.CreateModel(
            name='AuditorEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluation_date', models.DateField(verbose_name='Evaluation Date')),
                ('audited', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='auditor_evaluations', to='audits.audited', verbose_name='Audited')),
            ],
            options={
                'db_table': 'tb_auditor_evaluation',
            },
        ),
        migrations.CreateModel(
            name='LeadAuditorEvaluationQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=500, verbose_name='Question Text')),
                ('order', models.IntegerField(verbose_name='Order')),
                ('audited', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lead_auditor_questions', to='audits.audited', verbose_name='Audited')),
            ],
            options={
                'db_table': 'tb_lead_auditor_evaluation_question',
            },
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Area Name')),
                ('parent_area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='areas', to='audits.parentarea', verbose_name='Parent Area')),
            ],
            options={
                'db_table': 'tb_area',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last Name')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='people', to='audits.area', verbose_name='Area')),
                ('parent_area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='people', to='audits.parentarea', verbose_name='Parent Area')),
            ],
            options={
                'db_table': 'tb_person',
            },
        ),
        migrations.CreateModel(
            name='AuditTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_members', to='audits.auditrole', verbose_name='Role')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_roles', to='audits.person', verbose_name='Person')),
            ],
            options={
                'db_table': 'tb_audit_team',
            },
        ),
        migrations.AddField(
            model_name='audited',
            name='audited_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audited', to='audits.person', verbose_name='Audited Person'),
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Job Title')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='positions', to='audits.area', verbose_name='Area')),
                ('parent_area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='positions', to='audits.parentarea', verbose_name='Parent Area')),
            ],
            options={
                'db_table': 'tb_position',
            },
        ),
        migrations.AddField(
            model_name='person',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='audits.position', verbose_name='Job Position'),
        ),
        migrations.AddField(
            model_name='audited',
            name='requirement_level1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='audits.requirementlevel1', verbose_name='Requirement Level 1'),
        ),
        migrations.CreateModel(
            name='RequirementLevel2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Requirement Level 2')),
                ('level1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='level2_requirements', to='audits.requirementlevel1', verbose_name='Requirement Level 1')),
            ],
            options={
                'db_table': 'tb_requirement_level2',
            },
        ),
        migrations.AddField(
            model_name='audited',
            name='requirement_level2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='audits.requirementlevel2', verbose_name='Requirement Level 2'),
        ),
        migrations.CreateModel(
            name='RequirementLevel3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Requirement Level 3')),
                ('level1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='level3_requirements', to='audits.requirementlevel1', verbose_name='Requirement Level 1')),
                ('level2', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='level3_requirements', to='audits.requirementlevel2', verbose_name='Requirement Level 2')),
            ],
            options={
                'db_table': 'tb_requirement_level3',
            },
        ),
        migrations.CreateModel(
            name='Findings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finding_text', models.TextField(verbose_name='Finding')),
                ('classification', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='audits.findingclassification', verbose_name='Finding Classification')),
                ('requirement_level1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='audits.requirementlevel1', verbose_name='Requirement Level 1')),
                ('requirement_level2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='audits.requirementlevel2', verbose_name='Requirement Level 2')),
                ('requirement_level3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='audits.requirementlevel3', verbose_name='Requirement Level 3')),
            ],
            options={
                'db_table': 'tb_findings',
            },
        ),
        migrations.CreateModel(
            name='ChecklistQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirement_type', models.CharField(choices=[('level1', 'Requirement Level 1'), ('level2', 'Requirement Level 2'), ('level3', 'Requirement Level 3')], max_length=10, verbose_name='Requirement Type')),
                ('question_text', models.CharField(max_length=500, verbose_name='Question Text')),
                ('order', models.IntegerField(verbose_name='Order')),
                ('requirement_level1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='audits.requirementlevel1', verbose_name='Requirement Level 1')),
                ('requirement_level2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='audits.requirementlevel2', verbose_name='Requirement Level 2')),
                ('requirement_level3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='audits.requirementlevel3', verbose_name='Requirement Level 3')),
            ],
            options={
                'db_table': 'tb_checklist_question',
            },
        ),
        migrations.CreateModel(
            name='Checklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objective_evidence', models.TextField(verbose_name='Objective Evidence')),
                ('compliance', models.TextField(verbose_name='Compliance')),
                ('requirement_level1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='audits.requirementlevel1', verbose_name='Requirement Level 1')),
                ('requirement_level2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='audits.requirementlevel2', verbose_name='Requirement Level 2')),
                ('requirement_level3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='audits.requirementlevel3', verbose_name='Requirement Level 3')),
            ],
            options={
                'db_table': 'tb_checklist',
            },
        ),
        migrations.AddField(
            model_name='audited',
            name='requirement_level3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='audits.requirementlevel3', verbose_name='Requirement Level 3'),
        ),
        migrations.CreateModel(
            name='AssociatedElements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audit_date', models.DateField(verbose_name='Audit Date')),
                ('audit_time', models.CharField(max_length=50, verbose_name='Audit Time')),
                ('audit_location', models.CharField(max_length=200, verbose_name='Audit Location')),
                ('audit_team_member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='audits.auditteam', verbose_name='Audit Team Member')),
                ('requirement_level1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='audits.requirementlevel1', verbose_name='Requirement Level 1')),
                ('requirement_level2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='audits.requirementlevel2', verbose_name='Requirement Level 2')),
                ('requirement_level3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='audits.requirementlevel3', verbose_name='Requirement Level 3')),
            ],
            options={
                'db_table': 'tb_associated_elements',
            },
        ),
        migrations.CreateModel(
            name='AnnualProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField(verbose_name='Month')),
                ('year', models.IntegerField(verbose_name='Year')),
                ('requirement_level1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='audits.requirementlevel1', verbose_name='Requirement Level 1')),
                ('requirement_level2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='audits.requirementlevel2', verbose_name='Requirement Level 2')),
                ('requirement_level3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='audits.requirementlevel3', verbose_name='Requirement Level 3')),
            ],
            options={
                'db_table': 'tb_annual_program',
            },
        ),
    ]
