# Generated by Django 5.2.3 on 2025-06-24 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auditorevaluation',
            old_name='audit',
            new_name='audit_plan',
        ),
        migrations.RemoveField(
            model_name='findings',
            name='report',
        ),
        migrations.AddField(
            model_name='findings',
            name='audit_plan',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='findings', to='audits.annualplan', verbose_name='Audit'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='AnnualProgramUser',
        ),
    ]
