# Generated by Django 5.1.2 on 2025-03-23 15:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='audited',
            name='audited_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audited', to=settings.AUTH_USER_MODEL, verbose_name='Audited Person'),
        ),
        migrations.AlterField(
            model_name='auditteam',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_roles', to=settings.AUTH_USER_MODEL, verbose_name='Person'),
        ),
        migrations.AddField(
            model_name='area',
            name='groups',
            field=models.ManyToManyField(related_name='areas', to='auth.group'),
        ),
        migrations.AddField(
            model_name='area',
            name='users',
            field=models.ManyToManyField(related_name='areas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
