# Generated by Django 5.1.4 on 2025-04-07 15:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0002_alter_audited_audited_person_alter_auditteam_person_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='findings',
            name='classification',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='Finding Classification'),
        ),
        migrations.RemoveField(
            model_name='findings',
            name='requirement_level1',
        ),
        migrations.RemoveField(
            model_name='annualprogram',
            name='requirement_level1',
        ),
        migrations.RemoveField(
            model_name='associatedelements',
            name='requirement_level1',
        ),
        migrations.RemoveField(
            model_name='requirementlevel3',
            name='level1',
        ),
        migrations.RemoveField(
            model_name='audited',
            name='requirement_level1',
        ),
        migrations.RemoveField(
            model_name='checklist',
            name='requirement_level1',
        ),
        migrations.RemoveField(
            model_name='requirementlevel2',
            name='level1',
        ),
        migrations.RemoveField(
            model_name='associatedelements',
            name='requirement_level2',
        ),
        migrations.RemoveField(
            model_name='annualprogram',
            name='requirement_level2',
        ),
        migrations.RemoveField(
            model_name='findings',
            name='requirement_level2',
        ),
        migrations.RemoveField(
            model_name='audited',
            name='requirement_level2',
        ),
        migrations.RemoveField(
            model_name='requirementlevel3',
            name='level2',
        ),
        migrations.RemoveField(
            model_name='checklist',
            name='requirement_level2',
        ),
        migrations.RemoveField(
            model_name='associatedelements',
            name='requirement_level3',
        ),
        migrations.RemoveField(
            model_name='audited',
            name='requirement_level3',
        ),
        migrations.RemoveField(
            model_name='checklist',
            name='requirement_level3',
        ),
        migrations.RemoveField(
            model_name='annualprogram',
            name='requirement_level3',
        ),
        migrations.RemoveField(
            model_name='findings',
            name='requirement_level3',
        ),
        migrations.AlterModelOptions(
            name='checklist',
            options={'ordering': ['order']},
        ),
        migrations.RemoveField(
            model_name='audited',
            name='audited_person',
        ),
        migrations.RemoveField(
            model_name='auditedevaluationquestion',
            name='audited',
        ),
        migrations.RemoveField(
            model_name='auditorevaluation',
            name='audited',
        ),
        migrations.RemoveField(
            model_name='leadauditorevaluationquestion',
            name='audited',
        ),
        migrations.AddField(
            model_name='audited',
            name='audited_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='audited', to=settings.AUTH_USER_MODEL, verbose_name='Audited User'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auditedevaluationquestion',
            name='rating',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Rating'),
        ),
        migrations.AddField(
            model_name='checklist',
            name='order',
            field=models.IntegerField(default=2, verbose_name='Order'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='checklist',
            name='question_text',
            field=models.CharField(default=0, max_length=500, verbose_name='Question Text'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leadauditorevaluationquestion',
            name='rating',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Rating'),
        ),
        migrations.AlterField(
            model_name='auditteam',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_roles', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='compliance',
            field=models.TextField(blank=True, null=True, verbose_name='Compliance'),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='objective_evidence',
            field=models.TextField(blank=True, null=True, verbose_name='Objective Evidence'),
        ),
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Requirement Name')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sub_requirements', to='audits.requirement')),
            ],
            options={
                'db_table': 'tb_requirement',
            },
        ),
        migrations.AddField(
            model_name='annualprogram',
            name='requirement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='audits.requirement', verbose_name='Requirement'),
        ),
        migrations.AddField(
            model_name='associatedelements',
            name='requirement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='audits.requirement', verbose_name='Requirement'),
        ),
        migrations.AddField(
            model_name='audited',
            name='requirement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='audits.requirement', verbose_name='Requirement'),
        ),
        migrations.AddField(
            model_name='auditedevaluationquestion',
            name='requirement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='audits.requirement', verbose_name='Requirement'),
        ),
        migrations.AddField(
            model_name='auditorevaluation',
            name='requirement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='audits.requirement', verbose_name='Requirement'),
        ),
        migrations.AddField(
            model_name='auditreport',
            name='requirement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='audits.requirement', verbose_name='Requirement'),
        ),
        migrations.AddField(
            model_name='checklist',
            name='requirement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='audits.requirement', verbose_name='Requirement'),
        ),
        migrations.AddField(
            model_name='findings',
            name='requirement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='audits.requirement', verbose_name='Requirement'),
        ),
        migrations.AddField(
            model_name='leadauditorevaluationquestion',
            name='requirement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='audits.requirement', verbose_name='Requirement'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='audits.position')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='ChecklistQuestion',
        ),
        migrations.DeleteModel(
            name='FindingClassification',
        ),
        migrations.DeleteModel(
            name='RequirementLevel1',
        ),
        migrations.DeleteModel(
            name='RequirementLevel2',
        ),
        migrations.DeleteModel(
            name='RequirementLevel3',
        ),
    ]
