# Generated by Django 5.2.3 on 2025-06-24 21:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0002_rename_audit_auditorevaluation_audit_plan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditorevaluation',
            name='audit_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='auditor_evaluations', to='audits.annualplan', verbose_name='Audit Plan'),
        ),
        migrations.AlterField(
            model_name='auditreport',
            name='audit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='audits.annualplan', verbose_name='Audit Plan'),
        ),
        migrations.AlterField(
            model_name='findings',
            name='audit_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='findings', to='audits.annualplan', verbose_name='Audit Plan'),
        ),
    ]
