# Generated by Django 5.2.3 on 2025-06-26 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0003_alter_auditorevaluation_audit_plan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='findings',
            name='classification',
            field=models.CharField(choices=[('NC_MAYOR', 'No Conformidad Mayor'), ('NC_MENOR', 'No Conformidad Menor'), ('OPORTUNIDAD_MEJORA', 'Oportunidad de mejora')], max_length=20, verbose_name='Finding Classification'),
        ),
        migrations.AlterField(
            model_name='leadauditorevaluationquestion',
            name='type',
            field=models.TextField(choices=[('AUDITADO', 'Auditado'), ('AUDITOR_LIDER', 'Auditor Lider')], verbose_name='Type'),
        ),
    ]
