# Generated by Django 5.1.4 on 2025-04-22 16:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0003_alter_findings_classification_and_more'),
        ('company', '0002_area_parent_alter_area_name_alter_area_users_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnualPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audit_opening_date', models.DateField(verbose_name='Audit Opening Date')),
                ('audit_opening_time', models.TimeField(verbose_name='Audit Opening Time')),
                ('audit_opening_location', models.TextField(verbose_name='Audit Opening Location')),
                ('audit_closing_date', models.DateField(verbose_name='Audit Closing Date')),
                ('audit_closing_time', models.TimeField(verbose_name='Audit Closing Time')),
                ('audit_closing_location', models.TextField(verbose_name='Audit Closing Location')),
            ],
            options={
                'db_table': 'tb_audit_annual_plan',
            },
        ),
        migrations.CreateModel(
            name='AnnualPlanAuditor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'tb_audit_annual_plan_auditors',
            },
        ),
        migrations.CreateModel(
            name='AnnualProgramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'tb_audit_annual_program_users',
            },
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Process Name')),
            ],
            options={
                'db_table': 'tb_audit_process',
            },
        ),
        migrations.CreateModel(
            name='ProcessRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audits.process')),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.requirement')),
            ],
            options={
                'db_table': 'tb_audit_process_requirements',
            },
        ),
        migrations.RemoveField(
            model_name='area',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='area',
            name='parent_area',
        ),
        migrations.RemoveField(
            model_name='area',
            name='users',
        ),
        migrations.RemoveField(
            model_name='position',
            name='area',
        ),
        migrations.RemoveField(
            model_name='associatedelements',
            name='audit_team_member',
        ),
        migrations.RemoveField(
            model_name='associatedelements',
            name='requirement',
        ),
        migrations.RemoveField(
            model_name='audited',
            name='audited_user',
        ),
        migrations.RemoveField(
            model_name='audited',
            name='requirement',
        ),
        migrations.RemoveField(
            model_name='auditedevaluationquestion',
            name='requirement',
        ),
        migrations.RemoveField(
            model_name='auditorevaluation',
            name='requirement',
        ),
        migrations.DeleteModel(
            name='AuditPlanHeader',
        ),
        migrations.RemoveField(
            model_name='auditteam',
            name='role',
        ),
        migrations.RemoveField(
            model_name='auditteam',
            name='person',
        ),
        migrations.RemoveField(
            model_name='checklist',
            name='requirement',
        ),
        migrations.RemoveField(
            model_name='leadauditorevaluationquestion',
            name='requirement',
        ),
        migrations.RemoveField(
            model_name='position',
            name='parent_area',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='position',
        ),
        migrations.RemoveField(
            model_name='requirement',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='annualprogram',
            name='requirement',
        ),
        migrations.AlterField(
            model_name='findings',
            name='requirement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='company.requirement', verbose_name='Requirement'),
        ),
        migrations.RemoveField(
            model_name='auditreport',
            name='requirement',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='annualprogram',
            name='year',
        ),
        migrations.AddField(
            model_name='annualprogram',
            name='program_header',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, related_name='annual_programs', to='audits.auditprogramheader', verbose_name='Program Header'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auditprogramheader',
            name='year',
            field=models.IntegerField(default=4, verbose_name='Year'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auditreport',
            name='audit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='audits.annualprogram', verbose_name='Audit Plan'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='findings',
            name='report',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.PROTECT, to='audits.auditreport', verbose_name='Audit Report'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='annualprogram',
            name='month',
            field=models.PositiveSmallIntegerField(verbose_name='Month'),
        ),
        migrations.AlterField(
            model_name='findings',
            name='classification',
            field=models.CharField(choices=[('NC_MAYOR', 'NC_MAYOR'), ('NC_MENOR', 'NC_MENOR'), ('OPORTUNIDAD_MEJORA', 'OPORTUNIDAD_MEJORA')], max_length=20, verbose_name='Finding Classification'),
        ),
        migrations.AlterModelTable(
            name='annualprogram',
            table='tb_audit_annual_program',
        ),
        migrations.AlterModelTable(
            name='auditprogramheader',
            table='tb_audit_annual_program_headers',
        ),
        migrations.AlterModelTable(
            name='findings',
            table='tb_audit_findings',
        ),
        migrations.AddField(
            model_name='annualplan',
            name='annual_program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='annual_plans', to='audits.annualprogram', verbose_name='Annual Program'),
        ),
        migrations.AddField(
            model_name='annualplan',
            name='lider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='annual_plans', to=settings.AUTH_USER_MODEL, verbose_name='Audit Leader'),
        ),
        migrations.AddField(
            model_name='annualplanauditor',
            name='annual_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='auditors', to='audits.annualplan', verbose_name='Audit Plan'),
        ),
        migrations.AddField(
            model_name='annualplanauditor',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='auditors', to=settings.AUTH_USER_MODEL, verbose_name='Auditor'),
        ),
        migrations.AddField(
            model_name='annualprogramuser',
            name='annual_program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='users', to='audits.annualprogram', verbose_name='Annual Program'),
        ),
        migrations.AddField(
            model_name='annualprogramuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='annual_programs', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='annualprogram',
            name='process',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.PROTECT, related_name='annual_programs', to='audits.process', verbose_name='Process'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='process',
            name='requirements',
            field=models.ManyToManyField(related_name='processes', through='audits.ProcessRequirement', to='company.requirement', verbose_name='Associated Requirements'),
        ),
    ]
