# Generated by Django 5.1.4 on 2025-04-22 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0004_annualplan_annualplanauditor_annualprogramuser_and_more'),
        ('communications', '0006_alter_communicationtable_area'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Area',
        ),
        migrations.DeleteModel(
            name='AssociatedElements',
        ),
        migrations.DeleteModel(
            name='Audited',
        ),
        migrations.DeleteModel(
            name='AuditedEvaluationQuestion',
        ),
        migrations.DeleteModel(
            name='AuditorEvaluation',
        ),
        migrations.DeleteModel(
            name='AuditRole',
        ),
        migrations.DeleteModel(
            name='AuditTeam',
        ),
        migrations.DeleteModel(
            name='Checklist',
        ),
        migrations.DeleteModel(
            name='LeadAuditorEvaluationQuestion',
        ),
        migrations.DeleteModel(
            name='ParentArea',
        ),
        migrations.DeleteModel(
            name='Position',
        ),
        migrations.DeleteModel(
            name='Requirement',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
        migrations.AlterUniqueTogether(
            name='annualplanauditor',
            unique_together={('annual_plan', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='annualprogramuser',
            unique_together={('annual_program', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='processrequirement',
            unique_together={('process', 'requirement')},
        ),
    ]
