# Generated by Django 5.2.3 on 2025-06-27 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0004_alter_findings_classification_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annualplan',
            name='lider',
        ),
    ]
