# Generated by Django 5.2.3 on 2025-06-29 11:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0005_remove_annualplan_lider'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditreport',
            name='strengths',
        ),
        migrations.AddField(
            model_name='auditreport',
            name='conclusions',
            field=models.TextField(default=1, verbose_name='Conclusions'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auditreport',
            name='recommendations',
            field=models.TextField(default=0, verbose_name='Recommendations'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='auditedevaluationquestion',
            name='requirement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='audits.processrequirement', verbose_name='Requirement'),
        ),
        migrations.AlterField(
            model_name='findings',
            name='requirement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='audits.processrequirement', verbose_name='Requirement'),
        ),
        migrations.AlterField(
            model_name='processrequirement',
            name='requirement',
            field=models.CharField(max_length=200, verbose_name='Requirement Name'),
        ),
        migrations.CreateModel(
            name='CorrectiveAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corrective_action', models.TextField(verbose_name='Corrective Action')),
                ('due_date', models.DateField(verbose_name='Due Date')),
                ('audit_report', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='corrective_actions', to='audits.auditreport', verbose_name='Audit Report')),
                ('responsible_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Responsible User')),
            ],
            options={
                'db_table': 'tb_audit_corrective_actions',
            },
        ),
        migrations.CreateModel(
            name='CorrectiveActionFollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followup_date', models.DateField(verbose_name='Follow-up Date')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], max_length=50, verbose_name='Status')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='Comments')),
                ('corrective_action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followups', to='audits.correctiveaction', verbose_name='Corrective Action')),
            ],
            options={
                'db_table': 'tb_audit_corrective_actions_followup',
            },
        ),
    ]
