# Generated by Django 5.1.4 on 2025-04-24 17:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0005_delete_area_delete_associatedelements_delete_audited_and_more'),
        ('company', '0002_area_parent_alter_area_name_alter_area_users_and_more'),
        ('processes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadAuditorEvaluationQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(verbose_name='Question Text')),
                ('type', models.TextField(choices=[('AUDITADO', 'AUDITADO'), ('AUDITOR_LIDER', 'AUDITOR_LIDER')], verbose_name='Type')),
            ],
            options={
                'db_table': 'tb_audit_auditor_questions',
            },
        ),
        migrations.AlterField(
            model_name='annualprogram',
            name='process',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_annual_programs', to='processes.process', verbose_name='Process'),
        ),
        migrations.AlterField(
            model_name='processrequirement',
            name='process',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='processes.process'),
        ),
        migrations.CreateModel(
            name='AnnualPlanAudited',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annual_plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audited_users', to='audits.annualplan', verbose_name='Audit Plan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audited_users', to=settings.AUTH_USER_MODEL, verbose_name='Audited User')),
            ],
            options={
                'db_table': 'tb_audit_annual_plan_audited',
                'unique_together': {('annual_plan', 'user')},
            },
        ),
        migrations.CreateModel(
            name='AuditedEvaluationQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(verbose_name='Question Text')),
                ('requirement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='company.requirement', verbose_name='Requirement')),
            ],
            options={
                'db_table': 'tb_audit_checklist_questions',
            },
        ),
        migrations.CreateModel(
            name='AuditorEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.SmallIntegerField(verbose_name='Order in Checklist')),
                ('rate', models.IntegerField(verbose_name='Assigned Rating')),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='auditor_evaluations', to='audits.annualplan', verbose_name='Audit')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='auditor_evaluations', to='audits.auditedevaluationquestion', verbose_name='Question')),
            ],
            options={
                'db_table': 'tb_audit_auditor_evaluation',
            },
        ),
        migrations.CreateModel(
            name='Checklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveSmallIntegerField(verbose_name='Order')),
                ('compliance', models.BooleanField(verbose_name='Compliance')),
                ('evidence', models.TextField(blank=True, null=True, verbose_name='Objective Evidence')),
                ('audit_plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checklists', to='audits.annualplan', verbose_name='Audit Plan')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checklists', to='audits.auditedevaluationquestion', verbose_name='Question')),
            ],
            options={
                'db_table': 'tb_audit_checklist',
                'ordering': ['orden'],
            },
        ),
        migrations.DeleteModel(
            name='Process',
        ),
    ]
