# Generated by Django 5.2.3 on 2025-06-29 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0006_remove_auditreport_strengths_auditreport_conclusions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditreport',
            name='audit',
        ),
        migrations.AddField(
            model_name='auditreport',
            name='audit_plan',
            field=models.ForeignKey(db_column='audit_plan_id', default=1, on_delete=django.db.models.deletion.PROTECT, to='audits.annualplan', verbose_name='Audit Plan'),
            preserve_default=False,
        ),
    ]
