# Generated by Django 5.1.2 on 2026-03-22 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0007_remove_auditreport_audit_auditreport_audit_plan'),
        ('standards', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='processrequirement',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='processrequirement',
            name='requirement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='standards.standardrequirement', verbose_name='Standard Requirement'),
        ),
    ]
