# Generated by Django 5.1.2 on 2026-05-17 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0008_replace_requirement_charfield_with_fk'),
        ('standards', '0002_add_standard_mapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='annualprogram',
            name='standard',
            field=models.ForeignKey(blank=True, help_text='Norma que se auditará en este programa', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='annual_programs', to='standards.standard', verbose_name='Norma'),
        ),
    ]
