# Generated by Django 5.1.2 on 2026-05-21 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0009_add_standard_to_annual_program'),
        ('processes', '0010_processperformanceindicators_and_more'),
        ('standards', '0002_add_standard_mapping'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(help_text='Valor numérico del cumplimiento entre 0 y 1', verbose_name='Puntuación (0.0 - 1.0)')),
                ('category', models.CharField(choices=[('EXCELLENT', 'Excelente (≥85%)'), ('GOOD', 'Bueno (70-84%)'), ('PARTIAL', 'Parcial (50-69%)'), ('LOW', 'Bajo (25-49%)'), ('CRITICAL', 'Crítico (<25%)')], max_length=20, verbose_name='Categoría de Cumplimiento')),
                ('total_requirements', models.IntegerField(verbose_name='Total de Requisitos')),
                ('compliant_count', models.IntegerField(verbose_name='Requisitos Conformes')),
                ('non_compliant_count', models.IntegerField(verbose_name='Requisitos No Conformes')),
                ('insufficient_count', models.IntegerField(verbose_name='Requisitos con Evidencia Insuficiente')),
                ('not_evaluated_count', models.IntegerField(verbose_name='Requisitos No Evaluados')),
                ('calculated_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Cálculo')),
                ('detail', models.JSONField(default=dict, help_text='JSON con el detalle del cálculo por cada ProcessRequirement', verbose_name='Desglose por Requisito')),
                ('annual_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_snapshots', to='audits.annualplan', verbose_name='Plan de Auditoría')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compliance_snapshots', to='processes.process', verbose_name='Proceso')),
                ('standard', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compliance_snapshots', to='standards.standard', verbose_name='Norma')),
            ],
            options={
                'verbose_name': 'Snapshot de Cumplimiento',
                'verbose_name_plural': 'Snapshots de Cumplimiento',
                'db_table': 'tb_compliance_snapshots',
                'ordering': ['-calculated_at'],
            },
        ),
    ]
