# Generated by Django 5.1.2 on 2025-04-22 14:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField()),
            ],
            options={
                'db_table': 'tb_company_documentation_type',
            },
        ),
        migrations.CreateModel(
            name='ExternalClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
            options={
                'db_table': 'tb_company_external_client',
            },
        ),
        migrations.CreateModel(
            name='ExternalSupplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
            options={
                'db_table': 'tb_company_external_supplier',
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
            options={
                'db_table': 'tb_company_rol',
            },
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Area Name')),
                ('users', models.ManyToManyField(related_name='users', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tb_company_area',
            },
        ),
        migrations.CreateModel(
            name='Documentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_description', models.TextField()),
                ('document_code', models.TextField()),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='company_documentation', to='company.documentationtype')),
            ],
            options={
                'db_table': 'tb_company_documentation',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('code', models.TextField()),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='areas', to='company.area')),
                ('rol', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='roles', to='company.rol')),
            ],
            options={
                'db_table': 'tb_company_position',
            },
        ),
    ]
