# Generated by Django 5.1.4 on 2025-04-22 16:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sub_areas', to='company.area', verbose_name='Parent Area'),
        ),
        migrations.AlterField(
            model_name='area',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Area Name or Position Title'),
        ),
        migrations.AlterField(
            model_name='area',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='areas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Requirement Name')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sub_requirements', to='company.requirement')),
            ],
            options={
                'db_table': 'tb_company_requirement',
            },
        ),
    ]
