# Generated by Django 5.1.2 on 2025-04-29 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_area_parent_alter_area_name_alter_area_users_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentation',
            name='document_type',
        ),
        migrations.RemoveField(
            model_name='area',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='position',
            name='rol',
        ),
        migrations.DeleteModel(
            name='DocumentationType',
        ),
    ]
