# Generated by Django 5.2.3 on 2025-06-29 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_alter_userposition_position_alter_userposition_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalclient',
            name='country',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='externalclient',
            name='sector',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
