# Generated by Django 5.2.3 on 2025-06-29 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_externalclient_country_externalclient_sector'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalsupplier',
            name='country',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='externalsupplier',
            name='supply_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
