# Generated by Django 5.1.2 on 2024-12-02 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tb_channel',
            },
        ),
        migrations.CreateModel(
            name='CommunicationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(max_length=50)),
                ('direction', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tb_communication_type',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tb_department',
            },
        ),
        migrations.CreateModel(
            name='Periodicity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tb_periodicity',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'tb_role',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=240, null='Sin Asunto', verbose_name='Asunto del Mensaje')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('channels', models.ManyToManyField(related_name='channels', to='apps_unificado.channel', verbose_name='Canal de comunicación')),
                ('communication_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communication_type', to='apps_unificado.communicationtype', verbose_name='Tipo de Comunicación')),
                ('receivers', models.ManyToManyField(related_name='message_receivers', to='apps_unificado.department', verbose_name='Receptor')),
                ('transmitter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transmitter', to='apps_unificado.department', verbose_name='Emisor')),
                ('periodicity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_periodicity', to='apps_unificado.periodicity', verbose_name='Periodicidad')),
            ],
            options={
                'db_table': 'tb_message',
            },
        ),
        migrations.CreateModel(
            name='CommunicationTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('review_number', models.SmallIntegerField()),
                ('review_date', models.DateField()),
                ('approved_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approver', to='apps_unificado.department')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maker', to='apps_unificado.department')),
                ('reviewed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revisor', to='apps_unificado.department')),
                ('messages', models.ManyToManyField(related_name='messages', to='apps_unificado.message')),
            ],
            options={
                'db_table': 'tb_communication_table',
                'ordering': ['id'],
            },
        ),
    ]
