# Generated by Django 5.1.2 on 2024-12-02 11:21

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_unificado', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContingencyAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'tb_contingency_action',
            },
        ),
        migrations.CreateModel(
            name='Revision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=10, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='El código debe tener el formato: LLL-LLL-CC', regex='^[A-Za-z]{3}-[A-Za-z]{3}-\\d{2}$')])),
                ('review_number', models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], null=True)),
                ('review_date', models.DateField(blank=True, null=True)),
                ('update_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tb_revision',
            },
        ),
        migrations.CreateModel(
            name='RiskLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=50, unique=True)),
                ('color', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tb_risk_level',
            },
        ),
        migrations.CreateModel(
            name='ContingencyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('communicate_to', models.ManyToManyField(related_name='communicate_to_contingency', to='apps_unificado.role', verbose_name='Communicate To')),
                ('contingency_actions', models.ManyToManyField(to='apps_unificado.contingencyaction', verbose_name='Contingency Actions')),
                ('responsible', models.ManyToManyField(related_name='responsible_for_contingency', to='apps_unificado.role', verbose_name='Responsible')),
            ],
            options={
                'db_table': 'tb_contingency_plan',
            },
        ),
        migrations.CreateModel(
            name='Execution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approved_by', to='apps_unificado.role')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executed_by', to='apps_unificado.role')),
                ('reviewed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewed_by', to='apps_unificado.role')),
            ],
            options={
                'db_table': 'tb_execution',
            },
        ),
        migrations.CreateModel(
            name='RiskIdentification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_name', models.CharField(max_length=255)),
                ('identified_risk', models.CharField(max_length=255, unique=True)),
                ('consequences', models.TextField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risks', to='apps_unificado.department')),
            ],
            options={
                'db_table': 'tb_risk_identification',
            },
        ),
        migrations.CreateModel(
            name='RiskEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], verbose_name='Severity')),
                ('current_preventive_controls', models.TextField(blank=True, null=True, verbose_name='Current Preventive Controls')),
                ('occurrence', models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], verbose_name='Occurrence')),
                ('current_detection_controls', models.TextField(blank=True, null=True, verbose_name='Current Detection Controls')),
                ('detection', models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], verbose_name='Detection')),
                ('risk_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps_unificado.risklevel', verbose_name='Risk Level')),
            ],
            options={
                'db_table': 'tb_risk_evaluation',
            },
        ),
        migrations.CreateModel(
            name='Reevaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.PositiveIntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=0)),
                ('occurrence', models.PositiveIntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=0)),
                ('detection', models.PositiveIntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=0)),
                ('risk_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reevaluations', to='apps_unificado.risklevel')),
            ],
            options={
                'db_table': 'tb_reevaluation',
            },
        ),
        migrations.CreateModel(
            name='RiskTreatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treatment_action', models.TextField(verbose_name='Treatment Action')),
                ('target_date', models.DateField(verbose_name='Target Date')),
                ('actual_date', models.DateField(verbose_name='Actual Date')),
                ('responsible', models.ManyToManyField(to='apps_unificado.role', verbose_name='Responsible')),
            ],
            options={
                'db_table': 'tb_risk_treatment',
            },
        ),
    ]
