# Generated by Django 5.1.2 on 2024-12-02 11:32

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_unificado', '0002_contingencyaction_revision_risklevel_contingencyplan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='communicationtable',
            name='approved_by',
            field=models.ForeignKey(blank=True, default='Pending Approval', on_delete=django.db.models.deletion.CASCADE, related_name='approved_by', to='apps_unificado.department'),
        ),
        migrations.AlterField(
            model_name='communicationtable',
            name='code',
            field=models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message='El código debe tener el formato: LLL-LLL-CC', regex='^[A-Za-z]{3}-[A-Za-z]{3}-\\d{2}$')]),
        ),
        migrations.AlterField(
            model_name='communicationtable',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to='apps_unificado.department'),
        ),
        migrations.AlterField(
            model_name='communicationtable',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, default='Pending Review', on_delete=django.db.models.deletion.CASCADE, related_name='reviewed_by', to='apps_unificado.department'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='periodicity',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
