# Generated by Django 5.1.4 on 2025-01-21 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_unificado', '0003_alter_channel_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communicationtable',
            name='approved_by',
            field=models.ForeignKey(blank=True, default='Pending Approval', on_delete=django.db.models.deletion.PROTECT, related_name='approved_by', to='apps_unificado.department'),
        ),
        migrations.AlterField(
            model_name='communicationtable',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_by', to='apps_unificado.department'),
        ),
        migrations.AlterField(
            model_name='communicationtable',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, default='Pending Review', on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_by', to='apps_unificado.department'),
        ),
        migrations.AlterField(
            model_name='message',
            name='channels',
            field=models.ManyToManyField(related_name='channels', to='apps_unificado.channel', verbose_name='Communication Channel'),
        ),
        migrations.AlterField(
            model_name='message',
            name='communication_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='communication_type', to='apps_unificado.communicationtype', verbose_name='Communication Type'),
        ),
        migrations.AlterField(
            model_name='message',
            name='periodicity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='message_periodicity', to='apps_unificado.periodicity', verbose_name='Periodicity of Communicaation'),
        ),
        migrations.AlterField(
            model_name='message',
            name='subject',
            field=models.CharField(max_length=240, verbose_name='Asunto del Mensaje'),
        ),
        migrations.AlterField(
            model_name='message',
            name='transmitter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transmitter', to='apps_unificado.department', verbose_name='Emisor'),
        ),
    ]
