# Generated by Django 5.1.2 on 2024-12-02 10:52

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrmCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='images/company')),
                ('name', models.CharField(max_length=150)),
                ('owner_name', models.CharField(max_length=50)),
                ('industry_type', models.CharField(choices=[('', 'Select industry type'), ('Computer Industry', 'Computer Industry'), ('Chemical Industries', 'Chemical Industries'), ('Health Services', 'Health Services'), ('Telecommunications Services', 'Telecommunications Services'), ('Textiles: Clothing, Footwear', 'Textiles: Clothing, Footwear')], max_length=50)),
                ('rating', models.CharField(max_length=10)),
                ('location', models.CharField(max_length=150)),
                ('employee', models.CharField(max_length=10)),
                ('website', models.CharField(max_length=150)),
                ('contact_email', models.EmailField(max_length=150, unique=True)),
                ('since', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Crm Companies',
            },
        ),
        migrations.CreateModel(
            name='CrmContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='images/contact')),
                ('name', models.CharField(max_length=150)),
                ('company_name', models.CharField(max_length=150)),
                ('designation', models.CharField(max_length=150)),
                ('email_id', models.EmailField(max_length=150, unique=True)),
                ('phone', models.CharField(max_length=13)),
                ('lead_score', models.IntegerField()),
                ('tags', multiselectfield.db.fields.MultiSelectField(choices=[('Exiting', 'Exiting'), ('Lead', 'Lead'), ('Long-term', 'Long-term'), ('Partner', 'Partner')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CrmLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='images/leads')),
                ('name', models.CharField(max_length=50)),
                ('company_name', models.CharField(max_length=150)),
                ('lead_score', models.IntegerField()),
                ('phone', models.CharField(max_length=13)),
                ('location', models.CharField(max_length=150)),
                ('tags', multiselectfield.db.fields.MultiSelectField(choices=[('Exiting', 'Exiting'), ('Lead', 'Lead'), ('Long-term', 'Long-term'), ('Partner', 'Partner')], max_length=50)),
                ('create_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='EcommerceCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email_id', models.EmailField(max_length=50, unique=True)),
                ('phone', models.CharField(max_length=13)),
                ('joining_date', models.DateField()),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Block', 'Block')], max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='EcommerceOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('product', models.CharField(choices=[('Puma Tshirt', 'Puma Tshirt'), ('Adidas Sneakers', 'Adidas Sneakers'), ('350 ml Glass Grocery Container', '350 ml Glass Grocery Container'), ('American egale outfitters Shirt', 'American egale outfitters Shirt'), ('Galaxy Watch4', 'Galaxy Watch4'), ('Apple iPhone 12', 'Apple iPhone 12'), ('Funky Prints T-shirt', 'Funky Prints T-shirt'), ('USB Flash Drive Personalized with 3D Print', 'USB Flash Drive Personalized with 3D Print'), ('Oxford Button-Down Shirt', 'Oxford Button-Down Shirt'), ('Classic Short Sleeve Shirt', 'Classic Short Sleeve Shirt'), ('Half Sleeve T-Shirts (Blue)', 'Half Sleeve T-Shirts (Blue)'), ('Noise Evolve Smartwatch', 'Noise Evolve Smartwatch')], max_length=150)),
                ('order_date', models.DateTimeField()),
                ('amount', models.CharField(max_length=10)),
                ('payment_method', models.CharField(choices=[('Mastercard', 'Mastercard'), ('Visa', 'Visa'), ('COD', 'COD'), ('Paypal', 'Paypal')], max_length=50)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Inprogress', 'Inprogress'), ('Cancelled', 'Cancelled'), ('Pickups', 'Pickups'), ('Returns', 'Returns'), ('Delivered', 'Delivered')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='images/job/application')),
                ('company_name', models.CharField(max_length=150)),
                ('designation', models.CharField(max_length=150)),
                ('apply_date', models.DateField()),
                ('contact', models.CharField(max_length=13)),
                ('status', models.CharField(choices=[('Approved', 'Approved'), ('New', 'New'), ('Pending', 'Pending'), ('Rejected', 'Rejected')], max_length=15)),
                ('type', models.CharField(choices=[('Full Time', 'Full Time'), ('Part Time', 'Part Time')], max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='TicketList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('client_name', models.CharField(max_length=100)),
                ('assign_to', models.CharField(max_length=150)),
                ('create_date', models.DateField()),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('Closed', 'Closed'), ('Inprogress', 'Inprogress'), ('New', 'New'), ('Open', 'Open')], max_length=10)),
                ('priority', models.CharField(choices=[('High', 'High'), ('Low', 'Low'), ('Medium', 'Medium')], max_length=10)),
            ],
        ),
    ]
