# Generated by Django 5.1.2 on 2026-03-09 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Standard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ej: ISO 9001:2015 Sistemas de Gestión de Calidad', max_length=200, verbose_name='Nombre de la Norma')),
                ('version', models.CharField(help_text='Ej: 2015, Rev D', max_length=50, verbose_name='Versión')),
                ('sector', models.CharField(blank=True, help_text='Ej: General, Aeroespacial, Automotriz', max_length=100, null=True, verbose_name='Sector Industrial')),
                ('is_active', models.BooleanField(default=True, help_text='¿Esta norma está actualmente en uso?', verbose_name='Activa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
            ],
            options={
                'verbose_name': 'Norma',
                'verbose_name_plural': 'Normas',
                'db_table': 'tb_standards',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Clause',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Ej: 4.1, 7.2.1', max_length=20, verbose_name='Código de Cláusula')),
                ('title', models.CharField(max_length=500, verbose_name='Título')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('ordering', models.IntegerField(default=0, help_text='Orden de visualización dentro de la norma', verbose_name='Orden')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subclauses', to='standards.clause', verbose_name='Cláusula Padre')),
                ('standard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clauses', to='standards.standard', verbose_name='Norma')),
            ],
            options={
                'verbose_name': 'Cláusula',
                'verbose_name_plural': 'Cláusulas',
                'db_table': 'tb_standard_clauses',
                'ordering': ['standard', 'ordering', 'code'],
                'unique_together': {('standard', 'code')},
            },
        ),
        migrations.CreateModel(
            name='StandardRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Texto del Requisito')),
                ('mandatory', models.BooleanField(default=True, help_text='¿Este requisito es obligatorio para la certificación?', verbose_name='Obligatorio')),
                ('criticality_level', models.CharField(choices=[('low', 'Baja'), ('medium', 'Media'), ('high', 'Alta')], default='medium', max_length=10, verbose_name='Nivel de Criticidad')),
                ('is_extension', models.BooleanField(default=False, help_text='¿Este requisito es una extensión específica del sector?', verbose_name='Es Extensión')),
                ('ordering', models.IntegerField(default=0, help_text='Orden dentro de la cláusula', verbose_name='Orden')),
                ('clause', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='standards.clause', verbose_name='Cláusula')),
            ],
            options={
                'verbose_name': 'Requisito Normativo',
                'verbose_name_plural': 'Requisitos Normativos',
                'db_table': 'tb_standard_requirements',
                'ordering': ['clause', 'ordering'],
            },
        ),
    ]
