# Generated by Django 5.1.2 on 2026-05-01 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StandardMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mapping_type', models.CharField(choices=[('EQUIVALENT', 'Equivalente — mismo requisito en ambas normas'), ('SUPERSET', 'Superconjunto — AS9100 amplía el requisito de ISO 9001'), ('SUBSET', 'Subconjunto — AS9100 cubre solo una parte de ISO 9001'), ('RELATED', 'Relacionado — mismo tema, enfoque diferente'), ('NO_EQUIVALENT', 'Sin equivalente — requisito exclusivo de una norma')], max_length=20, verbose_name='Tipo de Mapeo')),
                ('notes', models.TextField(blank=True, help_text='Contexto adicional sobre la correspondencia entre requisitos', null=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('source_requirement', models.ForeignKey(help_text='Requisito de la norma base (ISO 9001)', on_delete=django.db.models.deletion.CASCADE, related_name='mappings_as_source', to='standards.standardrequirement', verbose_name='Requisito Origen')),
                ('target_requirement', models.ForeignKey(help_text='Requisito de la norma destino (AS9100)', on_delete=django.db.models.deletion.CASCADE, related_name='mappings_as_target', to='standards.standardrequirement', verbose_name='Requisito Destino')),
            ],
            options={
                'verbose_name': 'Mapeo Normativo',
                'verbose_name_plural': 'Mapeos Normativos',
                'db_table': 'tb_standard_mappings',
                'ordering': ['mapping_type'],
                'unique_together': {('source_requirement', 'target_requirement')},
            },
        ),
    ]
